logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

spring:
  thymeleaf:
    cache: false

security:
  oauth2:
    client:
      uaa:
        client-id: uaa
        client-secret: secret